name: Deploy to production
run-name: Deploy to production

on:
  push:
    branches:
      - main
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Some step for testing
        id: dummytest
        run: echo Hello world!
      - name: Run unit test
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "[ **${{ github.repository }}** ] unit tests finished with result: ${{ steps.dummytest.outcome }}"

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Some step for testing
        id: dummytest2
        run: echo Hello world!
      - name: Run unit test
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "[ **${{ github.repository }}** ] end-to-end tests finished with result: ${{ steps.dummytest2.outcome }}"

  deploy:
    needs: 
      - test
      - e2e
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK_URL}}
          content: "[ **${{ github.repository }}** ] deploy webhook post"

  notify:
    needs: 
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK_URL}}
          content: "[ **${{ github.repository }}** ] a new **deploy-to-production** request has been sent to server ⚠️"
