name: Action on push to the main/master branch
run-name: Deploy to production

on:
  push:
    branches:
      - main
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit test
      uses: tsickert/discord-webhook@v5.3.0
      with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK_URL}}
          content: "Unit test in ${{ github.repository }} has been finished with result: ${{ github.action_status }}"

  deploy:
    needs: 
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK_URL}}
          content: "A new DEPLOY TO PRODUCTION request has been sent to server from **${{ github.repository }}** repository"
