name: Action on push to the main branch
run-name: ${{ github.actor }} pushing changes to main branch

on:
  push:
    branches:
      - main
      - master

jobs:
  start-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notifi to Discord channel
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Sent from GitHub Actions using secrets"
