name: Action on push to the main branch
run-name: ${{ github.actor }} pushing changes to main branch

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit test
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "[${{ github.repository }}] Unit Test: PASS "
  start-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Discord channel
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "[${{ github.repository }}] Sent from GitHub Actions using secrets"
