name: Action on push to any branch
run-name: Run test to last commited changes on ${{ github.base_ref }} branch

on:
  push:
    branches:
      - '!master'
      - '!main'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit test
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Unit test in ${{ github.repository }} has been finished with result: ${{ github.action_status }}"
