name: Action on push to any branch
run-name: Run test to last commited changes

on: push

jobs:
    cancel:
        runs-on: ubuntu-lastest
        steps:
            -   name: Cancel any previous workflow still running
                uses: styfle/cancel-workflow-action

    test:
        runs-on: ubuntu-latest
        steps:
        -   name: Run unit test
            uses: tsickert/discord-webhook@v5.3.0
            with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                content: "Unit test in ${{ github.repository }} has been finished with result: ${{ github.action_status }}"

